add

diff --git a/scripts/k3s/join-k3s b/scripts/k3s/join-k3s
--- a/scripts/k3s/join-k3s
+++ b/scripts/k3s/join-k3s
@@ -37,8 +37,6 @@ scp  \
 ssh -i $IDENTIFY_FILE \
     -o PasswordAuthentication=no \
     "$NODE_IP" "warp-cli connect || true"
-scp -i $IDENTIFY_FILE \
-    "/etc/rancher/k3s/registries.yaml" "$NODE_IP:/etc/rancher/k3s/registries.yaml"
 scp \
     -i $IDENTIFY_FILE \
     /usr/local/share/ca-certificates/kubernetes.crt "$NODE_IP":/usr/local/share/ca-certificates/kubernetes.crt
@@ -57,7 +55,25 @@ ssh -i $IDENTIFY_FILE \
     -o PasswordAuthentication=no \
     "$NODE_IP" "k3s-killall.sh;k3s-agent-uninstall.sh;k3s-uninstall.sh;systemctl disable k3s-agent;systemctl disable k3s-agent" || true
 # 
-NODE_COMMAND="curl -fL https://get.k3s.io | K3S_NODE_NAME=$K3S_NODE_NAME sh -s - server --server $K3S_URL --token $K3S_TOKEN"
+# ( stat $HOME/k3s || wget "https://github.com/k3s-io/k3s/releases/download/v1.27.7+k3s1/k3s" -O $HOME/k3s) || (echo "Cannot download k3s. Please check your internet connection" && exit 1)
+ssh -i $IDENTIFY_FILE \
+    -o PasswordAuthentication=no \
+    "$NODE_IP" "( stat \$HOME/k3s )" || \
+ssh -i $IDENTIFY_FILE \
+    -o PasswordAuthentication=no \
+    "$NODE_IP" "(wget "https://github.com/k3s-io/k3s/releases/download/v1.27.7+k3s1/k3s" -O \$HOME/k3s) || (echo "Cannot download k3s. Please check your internet connection" && exit 1)" || exit 1
+# mv $HOME/k3s /usr/local/bin/ && chmod +x /usr/local/bin/k3s
+ssh -i $IDENTIFY_FILE \
+    -o PasswordAuthentication=no \
+    "$NODE_IP" "cp \$HOME/k3s /usr/local/bin/ && chmod +x /usr/local/bin/k3s"
+# 
+ssh -i $IDENTIFY_FILE \
+    -o PasswordAuthentication=no \
+    "$NODE_IP" "mkdir -p /etc/rancher/k3s/"
+scp -i $IDENTIFY_FILE \
+    $HOME/registries.yaml "$NODE_IP:/etc/rancher/k3s/registries.yaml"
+
+NODE_COMMAND="curl -fL https://get.k3s.io | INSTALL_K3S_SKIP_DOWNLOAD=true K3S_NODE_NAME=$K3S_NODE_NAME sh -s - server --server $K3S_URL --token $K3S_TOKEN"
 echo "Joining worker node to this cluster"
 echo "NODE_IP: $NODE_IP"
 ssh -i $IDENTIFY_FILE \
diff --git a/scripts/k3s/reinstall-k3s b/scripts/k3s/reinstall-k3s
--- a/scripts/k3s/reinstall-k3s
+++ b/scripts/k3s/reinstall-k3s
@@ -8,7 +8,7 @@ if [ ! -f $IDENTIFY_FILE ]; then
     echo "If you've already booted machines use ./pic FAI (Fully Automatic Installation), please upload $IDENTIFY_FILE in your github account"
     exit 1
 fi
-# 
+#
 PIC_DIR="$HOME/.pic"
 
 # ./pic uninstall-k3s $IDENTIFY_FILE
@@ -16,36 +16,48 @@ which k3s-uninstall.sh && k3s-uninstall.sh || true
 NODES=$(kubectl get nodes -o json | jq -r "[.items[] | .metadata.annotations.\"k3s.io/internal-ip\"]")
 NODES_IP=$(echo $NODES | jq -r '.[]')
 for node in $NODES_IP; do
-   if [ -z "$node" ]; then
-      continue
-   fi
-   ssh -o StrictHostKeyChecking=no -i $IDENTIFY_FILE $node "k3s-killall.sh;k3s-agent-uninstall.sh;k3s-uninstall.sh;systemctl disable k3s-agent;systemctl disable k3s-agent" || true
+    if [ -z "$node" ]; then
+        continue
+    fi
+    ssh -o StrictHostKeyChecking=no -i $IDENTIFY_FILE $node "k3s-killall.sh;k3s-agent-uninstall.sh;k3s-uninstall.sh;systemctl disable k3s-agent;systemctl disable k3s-agent" || true
 done
 rm -rf /var/lib/rook/
-# 
+#
 set -e -o pipefail
 K8S_MASTER_NODE_IP=$(hostname -I | cut -d' ' -f1)
 echo "K8S_MASTER_NODE_IP: $K8S_MASTER_NODE_IP"
 echo "Installing k3s"
 curl -fsSL https://get.docker.com -o install-docker.sh
-docker ps > /dev/null 2>&1 || sh install-docker.sh
+docker ps >/dev/null 2>&1 || sh install-docker.sh
 rm install-docker.sh || true
-kubectl > /dev/null 2>&1 || \
-    (curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" > /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl)
-helm version > /dev/null 2>&1 || \
+kubectl >/dev/null 2>&1 ||
+    (curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" >/usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl)
+helm version >/dev/null 2>&1 ||
     (curl https://get.helm.sh/helm-v3.13.1-linux-amd64.tar.gz -o helm-v3.13.1-linux-amd64.tar.gz && tar -xvf helm-v3.13.1-linux-amd64.tar.gz -C /usr/local/bin/ --strip-components=1 linux-amd64/helm)
 rm helm-v3.13.1-linux-amd64.tar.gz || true
-cloudflared  version || \
+cloudflared version ||
     (curl https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb)
-k9s info > /dev/null 2>&1 || \
+k9s info >/dev/null 2>&1 ||
     (wget -nc https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz -O k9s_Linux_amd64.tar.gz && tar -xvf k9s_Linux_amd64.tar.gz k9s && mv k9s /usr/local/bin/ && chmod +x /usr/local/bin/k9s)
 rm k9s_Linux_amd64.tar.gz || true
+( stat $HOME/k3s || wget "https://github.com/k3s-io/k3s/releases/download/v1.27.7+k3s1/k3s" -O $HOME/k3s) || (echo "Cannot download k3s. Please check your internet connection" && exit 1)
+cp $HOME/k3s /usr/local/bin/ && chmod +x /usr/local/bin/k3s
 # systemctl status nm-cloud-setup.service || apt install -y network-manager
 export NODE_IP=$(hostname -I | cut -d' ' -f1)
 export K3S_NODE_NAME="ip-"$(echo "$NODE_IP" | tr . -)
-time (curl -sfL https://get.k3s.io | K3S_NODE_NAME=$K3S_NODE_NAME sh -s - server --cluster-init)
+echo "mirrors:"                             >  $HOME/registries.yaml
+# 
+time ./pic Registry-as-a-pull-through-cache "$IDENTIFY_FILE" "$NODE_IP" "https://registry-1.docker.io"      "registry-1-docker-io"      "203.0.113.2" "docker.io"       | tee $LOGS_DIR/Registry-as-a-pull-through-cache.log
+time ./pic Registry-as-a-pull-through-cache "$IDENTIFY_FILE" "$NODE_IP" "https://quay.io"                   "quay-io"                   "203.0.113.3" "quay.io"         | tee $LOGS_DIR/Registry-as-a-pull-through-cache.log
+time ./pic Registry-as-a-pull-through-cache "$IDENTIFY_FILE" "$NODE_IP" "https://registry.k8s.io"           "registry-k8s-io"           "203.0.113.4" "registry.k8s.io" | tee $LOGS_DIR/Registry-as-a-pull-through-cache.log
+mkdir -p /etc/rancher/k3s/
+cp $HOME/registries.yaml /etc/rancher/k3s/registries.yaml
+#
+echo "Installing k3s"
+time (curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_DOWNLOAD=true K3S_NODE_NAME=$K3S_NODE_NAME sh -s - server --cluster-init)
 # /etc/systemd/system/k3s.service
-systemctl restart k3s
+echo "K3S_NODE_NAME: $K3S_NODE_NAME"
+# systemctl restart k3s
 K3S_URL="https://$K8S_MASTER_NODE_IP:6443"
 while ! cat /var/lib/rancher/k3s/server/token >/dev/null 2>&1; do
     echo "Waiting for K3S token"
@@ -56,16 +68,14 @@ cp /var/lib/rancher/k3s/server/tls/server-ca.crt /usr/local/share/ca-certificate
 update-ca-certificates
 mkdir -p ~/.kube
 cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
-
 while true; do
     kubectl -n kube-system rollout restart deployment coredns && break || echo "Retrying to restart coredns"
     sleep 2
 done
 kubectl get node -o wide
 kubectl label node $K3S_NODE_NAME added-numberth=1
-jq -n --arg k3s_url "$K3S_URL" --arg k3s_token "$K3S_TOKEN" '{"k3s_url":$k3s_url,"k3s_token":$k3s_token}' > "$PIC_DIR/k3s.json"
+jq -n --arg k3s_url "$K3S_URL" --arg k3s_token "$K3S_TOKEN" '{"k3s_url":$k3s_url,"k3s_token":$k3s_token}' >"$PIC_DIR/k3s.json"
 ./pic status
-
 
 if [ -f "NODES" ]; then
     NODES=$(cat NODES)
@@ -77,8 +87,7 @@ if [ -f "NODES" ]; then
         rm -rf $LOGS_DIR/join-k3s.log
     done
 fi
-exit 0
-
+exit 1
 if [ ! -f "NODES" ]; then
     echo "NODES file does not exist. Creating NODES file"
     nodesOnLan=$(./pic list-nodename $IDENTIFY_FILE | awk '{print $1}' | tr '\n' ' ')
@@ -92,7 +101,7 @@ if [ ! -f "NODES" ]; then
         time (./pic join-k3s "$node" $IDENTIFY_FILE) | tee $LOGS_DIR/join-k3s.log
         rm -rf $LOGS_DIR/join-k3s.log
     done
-done
+fi
 kubectl get node -o wide
 ./pic expose
 
