Update k3s version to v1.28.4+k3s2

diff --git a/scripts/k3s/reinstall-k3s b/scripts/k3s/reinstall-k3s
--- a/scripts/k3s/reinstall-k3s
+++ b/scripts/k3s/reinstall-k3s
@@ -94,7 +94,7 @@ cloudflared version ||
 k9s info >/dev/null 2>&1 ||
     (wget -nc https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz -O k9s_Linux_amd64.tar.gz && tar -xvf k9s_Linux_amd64.tar.gz k9s && mv k9s /usr/local/bin/ && chmod +x /usr/local/bin/k9s)
 rm k9s_Linux_amd64.tar.gz || true
-( stat $HOME/k3s || wget "https://github.com/k3s-io/k3s/releases/download/v1.27.7+k3s1/k3s" -O $HOME/k3s) || (echo "Cannot download k3s. Please check your internet connection" && exit 1)
+( stat $HOME/k3s || wget "https://github.com/k3s-io/k3s/releases/download/v1.28.4+k3s2/k3s" -O $HOME/k3s) || (echo "Cannot download k3s. Please check your internet connection" && exit 1)
 cp $HOME/k3s /usr/local/bin/ && chmod +x /usr/local/bin/k3s
 export NODE_IP=$(hostname -I | cut -d' ' -f1)
 export K3S_NODE_NAME="ip-"$(echo "$NODE_IP" | tr . -)
