Add directory creation step in sync-across-nodes script

diff --git a/scripts/storage/sync-across-nodes b/scripts/storage/sync-across-nodes
--- a/scripts/storage/sync-across-nodes
+++ b/scripts/storage/sync-across-nodes
@@ -13,6 +13,7 @@ for NODE in $NODES; do
     # if is ends with /, make directory
     if [[ $WORKDIR == */ ]]; then
         mkdir -p $WORKDIR
+        ssh -i /root/id_rsa $NODE "mkdir -p $WORKDIR || echo 'Failed to create directory'"
     fi
     # -a: archive mode
     # -v: verbose
@@ -20,7 +21,6 @@ for NODE in $NODES; do
     rsync -avz --info=progress2 \
         -e "ssh -i /root/id_rsa" $NODE:$WORKDIR $WORKDIR || echo "Failed to copy to $NODE"
     
-    ssh -i /root/id_rsa $NODE "mkdir -p $WORKDIR || echo 'Failed to create directory'"
     rsync -avz --info=progress2 \
         -e "ssh -i /root/id_rsa" $WORKDIR $NODE:$WORKDIR || echo "Failed to copy from $NODE"
 done
