Fix error handling in create-pipeline script

diff --git a/scripts/continuous-integration-deployment/create-pipeline b/scripts/continuous-integration-deployment/create-pipeline
--- a/scripts/continuous-integration-deployment/create-pipeline
+++ b/scripts/continuous-integration-deployment/create-pipeline
@@ -62,7 +62,7 @@ if [ "wait-for-success" == "$option2" ]; then
             --header "Authorization: Bearer $GITLAB_TOKEN" \
             $URL"s/"$PIPELINE_ID`
         PIPELINE_STATUS=$(echo $PIPELINE | jq -r ".status")
-        PIPELINE_ERROR=$(echo $PIPELINE | jq -r ".error")
+        PIPELINE_ERROR=$(echo $PIPELINE | jq -r ".error") || true
         if [ "invalid_token" == "$PIPELINE_ERROR" ]; then
             echo "Invalid token"
             GITLAB_TOKEN=$(./pic get-refresh-token-gitlab)
